### ISSUE TITLE
VCSCommit specific fields should be a `oneof`

### ISSUE THREAD

**Issue by unmultimedio** [bufbuild/registry-proto#13]
Some fields in [VCSCommit message](https://github.com/bufbuild/registry-proto/blob/4bdebb6d12f3ac76b9e354f438a0105d3612c8e8/buf/registry/module/v1beta1/vcs_commit.proto#L29) are probably too git-specific. I'm not 100% sure if all VCS systems we'd ever support contain a `string hash`, but certainly some concepts like the author, committer, or associated email information might not be present in other VCS systems.

What about

```diff
message VCSCommit {
  ...
+  // unsure if this one should live here at the root
  string hash = 4 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.max_len = 255
  ];
-  // The name of the author of the VCSCommit.
-  //
-  // VCS-specific: not associated with the name of Users on the BSR, for example.
-  string author_name = 11;
-  // The email of the author of the VCSCommit.
-  //
-  // VCS-specific: not associated with the Users on the BSR, for example.
-  string author_email = 12;
-  // The name of the committer of the VCSCommit.
-  //
-  // VCS-specific: not associated with the name of Users on the BSR, for example.
-  string committer_name = 13;
-  // The email of the committer of the VCSCommit.
-  //
-  // VCS-specific: not associated with the Users on the BSR, for example.
-  string committer_email = 14;
+  oneof metadata {
+    GitMetadata git_metadata; // this one will contain author/committer info
+    // other VCS metadata info
+  }
}
```

**Comment by bufdev** [comment]
- I think no matter what, `hash` should be at the root, as we consider this a unique property of the `VCSCommit` itself.
- I could go either way on this one. I think that for the lifetime of this version of the API being latest (2-3 years), I doubt we will support anything other than `git`. If we did, we can simply deprecate the existing fields. I worry that if we decide to introduce a `GitMetadata` type or similar (naming TBD), then we will have to remove `VCSType`, and say that "if the oneof message is present, this indicates that the VCSCommit is of this VCS type", which, if we don't have any data within `GitMetadata` (in the case that there's no author or committer information?), gets a bit wonky.

**Comment by nicksnyder** [comment]
VCSCommit was removed in https://github.com/bufbuild/registry-proto/pull/55
